name: coffee_shop_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/apple.png
    - assets/images/bottom_cap.png
    - assets/images/get_started.png
    - assets/images/google.png
    - assets/images/top_cap.png
    - assets/images/top_cap2.png
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
        - asset: assets/fonts/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Thin.ttf

